controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - jb_joint
      - b1_joint
      - b2_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: home