controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - jb_joint
      - b1_joint
      - b2_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint