arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains:
    joint1:
      p: 1000
      d: 1
      i: 1
      i_clamp: 0
    joint2:
      p: 1000
      d: 1
      i: 1
      i_clamp: 0
    joint3:
      p: 1000
      d: 1
      i: 1
      i_clamp: 0
    joint4:
      p: 1000
      d: 1
      i: 1
      i_clamp: 0
    joint5:
      p: 1000
      d: 1
      i: 1
      i_clamp: 0
    joint6:
      p: 1000
      d: 1
      i: 1
      i_clamp: 0
